name: Continuous integration

on:
  pull_request: null
  push:
    branches:
      - main
      - develop

jobs:
  coding-styles-8-0:
    runs-on: ubuntu-22.04
    env:
      extensions: 'openswoole, gd, intl'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup cache environment
        id: extcache
        uses: shivammathur/cache-extensions@v1
        with:
          php-version: '8.0'
          extensions: ${{ env.extensions }}
          key: coding-styles-extensions
      - name: Cache extensions
        uses: actions/cache@v2
        with:
          path: ${{ steps.extcache.outputs.dir }}
          key: ${{ steps.extcache.outputs.key }}
          restore-keys: ${{ steps.extcache.outputs.key }}
      - name: Use PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
          tools: composer
          extensions: ${{ env.extensions }}
      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist
      - name: Check coding styles
        run: composer coding-styles

  static-analysis-8-0:
    runs-on: ubuntu-22.04
    env:
      extensions: 'openswoole, gd, intl'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup cache environment
        id: extcache
        uses: shivammathur/cache-extensions@v1
        with:
          php-version: '8.0'
          extensions: ${{ env.extensions }}
          key: coding-styles-extensions
      - name: Cache extensions
        uses: actions/cache@v2
        with:
          path: ${{ steps.extcache.outputs.dir }}
          key: ${{ steps.extcache.outputs.key }}
          restore-keys: ${{ steps.extcache.outputs.key }}
      - name: Use PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
          tools: composer
          extensions: ${{ env.extensions }}
      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist
      - name: Static analysis
        run: composer static-analysis

  unit-tests-8-0:
    runs-on: ubuntu-22.04
    env:
      extensions: 'openswoole, gd, intl'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup cache environment
        id: extcache
        uses: shivammathur/cache-extensions@v1
        with:
          php-version: '8.0'
          extensions: ${{ env.extensions }}
          key: coding-styles-extensions
      - name: Cache extensions
        uses: actions/cache@v2
        with:
          path: ${{ steps.extcache.outputs.dir }}
          key: ${{ steps.extcache.outputs.key }}
          restore-keys: ${{ steps.extcache.outputs.key }}
      - name: Use PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
          tools: composer
          extensions: ${{ env.extensions }}
          coverage: pcov
          ini-values: pcov.directory=module
      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist
      - name: Unit tests
        run: composer test:unit

  unit-tests-8-1:
    runs-on: ubuntu-22.04
    env:
      extensions: 'openswoole'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup cache environment
        id: extcache
        uses: shivammathur/cache-extensions@v1
        with:
          php-version: '8.1'
          extensions: ${{ env.extensions }}
          key: coding-styles-extensions
      - name: Cache extensions
        uses: actions/cache@v2
        with:
          path: ${{ steps.extcache.outputs.dir }}
          key: ${{ steps.extcache.outputs.key }}
          restore-keys: ${{ steps.extcache.outputs.key }}
      - name: Use PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          tools: composer
          extensions: ${{ env.extensions }}
          coverage: pcov
          ini-values: pcov.directory=module
      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist
      - name: Unit tests
        run: composer test:unit
      - name: Publish coverage
        uses: actions/upload-artifact@v3
        with:
          name: coverage-unit
          path: |
            build/coverage-unit

  e2e-tests-8-0:
    runs-on: ubuntu-22.04
    env:
      extensions: 'openswoole, gd, intl'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup cache environment
        id: extcache
        uses: shivammathur/cache-extensions@v1
        with:
          php-version: '8.0'
          extensions: ${{ env.extensions }}
          key: coding-styles-extensions
      - name: Cache extensions
        uses: actions/cache@v2
        with:
          path: ${{ steps.extcache.outputs.dir }}
          key: ${{ steps.extcache.outputs.key }}
          restore-keys: ${{ steps.extcache.outputs.key }}
      - name: Use PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
          tools: composer
          extensions: ${{ env.extensions }}
          coverage: pcov
          ini-values: pcov.directory=module
      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist
      - name: E2E tests
        run: composer test:e2e

  e2e-tests-8-1:
    runs-on: ubuntu-22.04
    env:
      extensions: 'openswoole'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup cache environment
        id: extcache
        uses: shivammathur/cache-extensions@v1
        with:
          php-version: '8.1'
          extensions: ${{ env.extensions }}
          key: coding-styles-extensions
      - name: Cache extensions
        uses: actions/cache@v2
        with:
          path: ${{ steps.extcache.outputs.dir }}
          key: ${{ steps.extcache.outputs.key }}
          restore-keys: ${{ steps.extcache.outputs.key }}
      - name: Use PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          tools: composer
          extensions: ${{ env.extensions }}
          coverage: pcov
          ini-values: pcov.directory=module
      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist
      - name: E2E tests
        run: composer test:e2e
      - name: Publish coverage
        uses: actions/upload-artifact@v3
        with:
          name: coverage-e2e
          path: |
            build/coverage-e2e

  unit-mutation-tests:
    runs-on: ubuntu-22.04
    needs:
      - unit-tests-8-1
    env:
      extensions: 'openswoole'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup cache environment
        id: extcache
        uses: shivammathur/cache-extensions@v1
        with:
          php-version: '8.1'
          extensions: ${{ env.extensions }}
          key: coding-styles-extensions
      - name: Cache extensions
        uses: actions/cache@v2
        with:
          path: ${{ steps.extcache.outputs.dir }}
          key: ${{ steps.extcache.outputs.key }}
          restore-keys: ${{ steps.extcache.outputs.key }}
      - name: Use PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          tools: composer
          extensions: ${{ env.extensions }}
          coverage: pcov
          ini-values: pcov.directory=module
      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist
      - name: Download coverage
        uses: actions/download-artifact@v3
        with:
          name: coverage-unit
          path: build
      - name: Unit mutation tests
        run: composer mutation-tests:unit

  e2e-mutation-tests:
    runs-on: ubuntu-22.04
    needs:
      - e2e-tests-8-1
    env:
      extensions: 'openswoole'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup cache environment
        id: extcache
        uses: shivammathur/cache-extensions@v1
        with:
          php-version: '8.1'
          extensions: ${{ env.extensions }}
          key: coding-styles-extensions
      - name: Cache extensions
        uses: actions/cache@v2
        with:
          path: ${{ steps.extcache.outputs.dir }}
          key: ${{ steps.extcache.outputs.key }}
          restore-keys: ${{ steps.extcache.outputs.key }}
      - name: Use PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          tools: composer
          extensions: ${{ env.extensions }}
          coverage: pcov
          ini-values: pcov.directory=module
      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist
      - name: Download coverage
        uses: actions/download-artifact@v3
        with:
          name: coverage-unit
          path: build
      - name: E2E mutation tests
        run: composer mutation-tests:e2e
