name: Continuous integration

on:
  pull_request: null
  push:
    branches:
      - main
      - develop

jobs:
  static-checks:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        command: ['soding-styles', 'static-analysis']
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup
        uses: './.github/actions/ci-setup'
        with:
          php-version: '8.1'
          php-extensions: 'openswoole, gd, intl'
          extensions-cache-key: e2e-tests-${{ matrix.command }}
      - name: Run ${{ matrix.command }} with composer
        run: composer ${{ matrix.command }}

  unit-tests:
    uses: './.github/workflows/ci-test.yml'
    with:
      test-group: unit

  e2e-tests:
    uses: './.github/workflows/ci-test.yml'
    with:
      test-group: e2e
